rm_hw:
  bus:
    - can0
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  # Configurations of the actuators
  actuators:
    joint1:
      bus: can0
      id: 0x201
      type: rm_2006
      lp_cutoff_frequency: 150
  #     need calibration: true  #set to true when this actuator need to be calibrated and it defaults to false when it is not been set.
